# Nexys4 Pin Assignments
############################
# On-board Slide Switches  #
############################
set_property PACKAGE_PIN J15 [get_ports swt[0]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[0]]
set_property PACKAGE_PIN L16 [get_ports swt[1]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[1]]
set_property PACKAGE_PIN M13 [get_ports swt[2]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[2]]
set_property PACKAGE_PIN R15 [get_ports swt[3]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[3]]
set_property PACKAGE_PIN R17 [get_ports swt[4]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[4]]
set_property PACKAGE_PIN T18 [get_ports swt[5]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[5]]
set_property PACKAGE_PIN U18 [get_ports swt[6]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[6]]
set_property PACKAGE_PIN R13 [get_ports swt[7]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[7]]
set_property PACKAGE_PIN T8 [get_ports swt[8]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[8]]
set_property PACKAGE_PIN U8 [get_ports swt[9]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[9]]
set_property PACKAGE_PIN R16 [get_ports swt[10]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[10]]
set_property PACKAGE_PIN T13 [get_ports swt[11]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[11]]
set_property PACKAGE_PIN H6 [get_ports swt[12]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[12]]
set_property PACKAGE_PIN U12 [get_ports swt[13]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[13]]
set_property PACKAGE_PIN U11 [get_ports swt[14]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[14]]
set_property PACKAGE_PIN V10 [get_ports swt[15]]
set_property IOSTANDARD LVCMOS33 [get_ports swt[15]]

############################
# On-board led             #
############################
set_property PACKAGE_PIN H17 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property PACKAGE_PIN K15 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property PACKAGE_PIN J13 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property PACKAGE_PIN N14 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property PACKAGE_PIN R18 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property PACKAGE_PIN V17 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property PACKAGE_PIN U17 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property PACKAGE_PIN U16 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property PACKAGE_PIN V16 [get_ports led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports led[8]]
set_property PACKAGE_PIN T15 [get_ports led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports led[9]]
set_property PACKAGE_PIN U14 [get_ports led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports led[10]]
set_property PACKAGE_PIN T16 [get_ports led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports led[11]]
set_property PACKAGE_PIN V15 [get_ports led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports led[12]]
set_property PACKAGE_PIN V14 [get_ports led[13]]
set_property IOSTANDARD LVCMOS33 [get_ports led[13]]
set_property PACKAGE_PIN V12 [get_ports led[14]]
set_property IOSTANDARD LVCMOS33 [get_ports led[14]]
set_property PACKAGE_PIN V11 [get_ports led[15]]
set_property IOSTANDARD LVCMOS33 [get_ports led[15]]




